### ISSUE TITLE
聖遺物が一箇所以上付与されていないキャラクターの画像生成に失敗する

### ISSUE THREAD

**Issue by ivixvi** [shaaaaaQ/ArtifacterImageGen#1]
genshin-discord-botにbuild_cardがついにマージされた喜びで、動作確認をしていたところたまたま発見しました。

エラーの発生箇所は以下かと思います。Noneチェックで解決するかもしれません。
https://github.com/shaaaaaQ/ArtifacterImageGen/blob/master/artifacter_image_gen/generator.py#L174

### エラー内容の共有
<details>
<summary> スタックトレースを開く </summary>

```sh
2023-04-18 13:40:17 ERROR    discord.ui.view Ignoring exception in view <View timeout=180.0 children=3> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='生成' emoji=None row=None>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/process.py", line 256, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/artifacter_image_gen/generator.py", line 188, in generate
    score = self.calc_score(rates)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/artifacter_image_gen/generator.py", line 174, in calc_score       
    for stat in artifact.detail.substats:
                ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'detail'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/ui/view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "/home/cogs/build_card.py", line 88, in generate
    image = future.result()
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
AttributeError: 'NoneType' object has no attribute 'detail'
```

</details>

**Comment by ivixvi** [comment]
今週末にもで確認して着手してそうなPRがなければ直しちゃおうかなと考えています。

**Comment by shaaaaaQ** [comment]
報告ありがとうございます
多分直りました

**Comment by ivixvi** [comment]
対応ありがとうございます！
こちらでも動作確認し、直っていることを確認できました。
